# Cloudflare Pages configuration
name = "haas-blog"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Environment variables
[vars]
ENVIRONMENT = "production"

# KV namespace bindings for functions
[[kv_namespaces]]
binding = "SUBSCRIBERS"
id = "da9ea499f9534d1ba78cd9a3a381ae2a"

[[kv_namespaces]]
binding = "RATE_LIMIT" 
id = "12a9dd7606564fe9a3261bfab8de9d5a"

# Performance metrics storage
[[kv_namespaces]]
binding = "METRICS_KV"
id = "d9bb6ce681f141678a85b5204d3908bd"  # Replace with actual KV namespace ID