name: Auto Update Blog Metadata

on:
  push:
    branches: [main]
    paths:
      - 'src/posts/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-blog-metadata:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate blog metadata and images
        run: |
          bun run generate-metadata
          bun run generate-rss
          bun run generate-sitemap
          bun run generate-blog-images
          bun run generate-fallbacks

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add public
            git commit -m "chore: auto update blog metadata" || echo "No changes to commit"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
