name: Cleanup Preview Deployments

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    name: Cleanup Preview Deployment
    
    steps:
      - name: Delete Preview Deployment
        uses: actions/github-script@v7
        with:
          script: |
            // Comment on the PR about cleanup
            const commentBody = `## 🧹 Preview cleanup

            Preview deployment for this PR has been automatically cleaned up.
            
            **Branch:** \`${{ github.head_ref }}\`
            **Environment:** \`preview-${{ github.event.number }}\`
            
            ---
            *Cleanup completed at: ${new Date().toISOString()}*`;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });

            // Update deployment status to inactive
            const { data: deployments } = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment: `preview-${{ github.event.number }}`,
              per_page: 100
            });

            for (const deployment of deployments) {
              await github.rest.repos.createDeploymentStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                deployment_id: deployment.id,
                state: 'inactive',
                description: 'Preview deployment cleaned up after PR closure'
              });
            }