name: Production Build Validation

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  validate-production:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    name: Validate Production Build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run type check
        run: bun run typecheck

      - name: Run linting
        run: bun run lint

      - name: Build project
        run: bun run build
        env:
          VITE_RESEND_API_KEY: ${{ secrets.VITE_RESEND_API_KEY }}
          VITE_EMAIL_TO: ${{ secrets.VITE_EMAIL_TO }}
          VITE_EMAIL_FROM: ${{ secrets.VITE_EMAIL_FROM }}

      - name: Run deployment health check
        run: bun run check:deploy
        env:
          VITE_RESEND_API_KEY: ${{ secrets.VITE_RESEND_API_KEY }}
          VITE_EMAIL_TO: ${{ secrets.VITE_EMAIL_TO }}
          VITE_EMAIL_FROM: ${{ secrets.VITE_EMAIL_FROM }}

      - name: Validate production build
        run: |
          echo "✅ Production build validated successfully!"
          echo "🚀 Cloudflare Pages will automatically deploy this commit"
          echo "📦 Build size: $(du -sh dist | cut -f1)"
