name: Comprehensive Quality Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Run TypeScript checks
        run: bun run typecheck
      
      - name: Run ESLint
        run: bun run lint
      
      - name: Check Prettier formatting
        run: bun run prettier:check
      
      - name: Run Markdown linting
        run: bun run lint:md
        continue-on-error: true
      
      - name: Run spell check
        run: bun run spell
        continue-on-error: true
      
      - name: Validate SEO
        run: bun run validate:seo
        continue-on-error: true
      
      - name: Check bundle size
        run: bun run check:deploy
        continue-on-error: true
      
      - name: Run all checks summary
        run: bun run check:all
        if: always()
      
      - name: Comment PR with results
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `
            ## 🔍 Quality Check Results
            
            | Check | Status |
            |-------|--------|
            | TypeScript | ${{ steps.typecheck.outcome == 'success' && '✅' || '❌' }} |
            | ESLint | ${{ steps.lint.outcome == 'success' && '✅' || '❌' }} |
            | Prettier | ${{ steps.prettier.outcome == 'success' && '✅' || '❌' }} |
            | Markdown Lint | ${{ steps.markdown.outcome == 'success' && '✅' || '⚠️' }} |
            | Spell Check | ${{ steps.spell.outcome == 'success' && '✅' || '⚠️' }} |
            | SEO Validation | ${{ steps.seo.outcome == 'success' && '✅' || '⚠️' }} |
            | Bundle Size | ${{ steps.bundle.outcome == 'success' && '✅' || '⚠️' }} |
            
            > ✅ Required checks | ⚠️ Optional checks with warnings
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });