name: Stale PR Check

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: read
  checks: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Claude on stale failing PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const STALE_HOURS = 12;
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });
            const now = new Date();
            for (const pr of prs) {
              const updated = new Date(pr.updated_at);
              const hours = (now - updated) / 36e5;
              if (hours < STALE_HOURS) continue;

              const { data: checks } = await github.rest.checks.listForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: pr.head.sha,
              });
              const failing = checks.check_runs.filter(c => ['failure', 'timed_out', 'cancelled'].includes(c.conclusion));
              if (failing.length === 0) continue;

              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
              });
              const already = comments.some(c => c.body.includes('<!-- stale-pr-claude -->'));
              if (already) continue;
              const failureList = failing.map(c => `- ${c.name}`).join('\n');
              const body = `<!-- stale-pr-claude -->\nHey @claude, this PR has been inactive for over 12 hours and the following checks are failing:\n${failureList}\nPlease investigate and push fixes.`;
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body,
              });
            }
